<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ur5_test" >

	<!-- Arbitrary offsets for shoulder/elbow joints -->
	<!-- shoulder_offset - elbow_offset + wrist_1_length = 0.10915 -->
	<xacro:property name="shoulder_offset" value="0.13585" />  <!-- measured from model -->
	<xacro:property name="elbow_offset" value="0.1197" /> <!-- measured from model -->
	
	<!-- Inertia parameters -->
	<xacro:property name="base_mass" value="4.0" />  <!-- This mass might be incorrect -->
	<xacro:property name="shoulder_mass" value="3.7000" />
	<xacro:property name="upper_arm_mass" value="8.3930" />
	<xacro:property name="forearm_mass" value="2.2750" />
	<xacro:property name="wrist_1_mass" value="1.2190" />
	<xacro:property name="wrist_2_mass" value="1.2190" />
	<xacro:property name="wrist_3_mass" value="0.1879" />

	<!-- link lengths used in model -->
	<xacro:property name="shoulder_height" value="0.089159" />
	<xacro:property name="upper_arm_length" value="0.42500" />
	<xacro:property name="forearm_length" value="0.39225" />
	<xacro:property name="wrist_1_length" value="0.093" />	<!-- CAD measured -->
	<xacro:property name="wrist_2_length" value="0.09465" />	<!-- In CAD this distance is 0.930, but in the spec it is 0.09465 -->
	<xacro:property name="wrist_3_length" value="0.0823" />

	<xacro:property name="shoulder_radius" value="0.060" />   <!-- manually measured -->
	<xacro:property name="upper_arm_radius" value="0.054" />  <!-- manually measured -->
	<xacro:property name="elbow_radius" value="0.060" />      <!-- manually measured -->
	<xacro:property name="forearm_radius" value="0.040" />    <!-- manually measured -->
	<xacro:property name="wrist_radius" value="0.045" />      <!-- manually measured -->
	
	<xacro:property name="box_dim" value="0.140" />      <!-- proposed -->
	
	<!-- Helper macros -->
	<xacro:macro name="inertial_macro" params="radius length mass">
		<inertial>
			<mass value="${mass}" />
			<inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
				iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
				izz="${0.5 * mass * radius * radius}" />
		</inertial>
	</xacro:macro>
	
	<xacro:macro name="box_visual" params="box_size *origin" >
		<visual>
			<geometry>
				<box size="${box_size} ${box_size} ${box_size}" />
			</geometry>
			<xacro:insert_block name="origin" />
			<material name="LightBlue">
				<color rgba="0.0 0.8 0.8 1.0"/>
			</material>
		</visual>
	</xacro:macro>
	
	<xacro:macro name="cylinder_visual" params="radius length *origin" >
		<visual>
			<geometry>
				<cylinder length="${length}" radius="${radius}"/>
			</geometry>
			<xacro:insert_block name="origin" />
			<material name="Gray">
				<color rgba="0.8 0.8 0.8 1.0"/>
			</material>
		</visual>
	</xacro:macro>



	<!-- Macro for links -->
	<!-- Generic link -->
	<xacro:macro name="cylinder_link" params="name radius length box_size mass">
		<link name="${name}">
		
			<xacro:inertial_macro radius="${radius}" length="${length}" mass="${mass}"/>
		
			<xacro:box_visual box_size="${box_size}">
				<origin xyz="0 0 ${length}" rpy="0 0 0"/>
			</xacro:box_visual>
			
			<xacro:cylinder_visual radius="${radius}" length="${length}">
				<origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
			</xacro:cylinder_visual>
			
			<xacro:box_visual box_size="${box_size}">
				<origin xyz="0 0 0" rpy="0 0 0"/>
			</xacro:box_visual>
			
		</link> 
	</xacro:macro>
	
	<!-- Base -->
	<xacro:macro name="single_link" params="name radius length box_size mass">
		<link name="${name}">
		
			<xacro:inertial_macro radius="${radius}" length="${length}" mass="${mass}"/>
			
			<xacro:cylinder_visual radius="${radius}" length="${length}">
				<origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
			</xacro:cylinder_visual>
			
			<xacro:box_visual box_size="${box_size}">
				<origin xyz="0 0 ${length}" rpy="0 0 0"/>
			</xacro:box_visual>
			
		</link> 
	</xacro:macro>
	
	<!-- Wrist -->
	<xacro:macro name="wrist_link" params="name radius length box_size mass">
		<link name="${name}">
			
			<xacro:inertial_macro radius="${radius}" length="${length}" mass="${mass}"/>
			
			<xacro:box_visual box_size="${box_size}">
				<origin xyz="0 0 0" rpy="0 0 0"/>
			</xacro:box_visual>
			
		</link> 
	</xacro:macro>
	
	<!-- Macro for joints -->
	<xacro:macro name="ur_joint" params="name parent child *origin *axis">
		<joint name="${name}" type="revolute">
			<xacro:insert_block name="origin" />
			<xacro:insert_block name="axis" />
			<limit lower="-3.1416" upper="3.1416" effort="150" velocity="3.1416" />
			<child link="${child}" />
			<parent link="${parent}" />
		</joint>
	</xacro:macro>
	
	<!-- Links -->
	<link name="base_link"/>
	<xacro:single_link name="square_base" radius="${shoulder_radius}" length="${shoulder_height}" box_size="${shoulder_offset}"
		mass = "${shoulder_mass}"/>
	<xacro:cylinder_link name="upper_arm_link" radius="${upper_arm_radius}" length="${upper_arm_length}" box_size="${shoulder_offset}"
		mass = "${upper_arm_mass}"/>
	<xacro:cylinder_link name="forearm_link" radius="${forearm_radius}" length="${forearm_length}" box_size="${elbow_offset}"
		mass = "${forearm_mass}"/>
	<xacro:wrist_link name="wrist_1_link" radius="${wrist_radius}" length="${wrist_1_length}" box_size="${elbow_offset}"
		mass = "${wrist_1_mass}"/>
	<xacro:wrist_link name="wrist_2_link" radius="${wrist_radius}" length="${wrist_2_length}" box_size="${elbow_offset}"
		mass = "${wrist_2_mass}"/>
	<xacro:wrist_link name="wrist_3_link" radius="${wrist_radius}" length="${wrist_3_length}" box_size="${elbow_offset}"
		mass = "${wrist_3_mass}"/>
	
	<!-- Joints -->
	<xacro:ur_joint name="base" parent="base_link" child="square_base">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<axis xyz="0 0 1"/>
	</xacro:ur_joint>
	
	<xacro:ur_joint name="shoulder" parent="square_base" child="upper_arm_link">
		<origin xyz="${shoulder_offset} 0 ${shoulder_height}" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
	</xacro:ur_joint>

	<xacro:ur_joint name="elbow" parent="upper_arm_link" child="forearm_link">
		<origin xyz="${-elbow_offset} 0 ${upper_arm_length}" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
	</xacro:ur_joint>

	<xacro:ur_joint name="wrist_1" parent="forearm_link" child="wrist_1_link">
		<origin xyz="${elbow_offset} 0 ${forearm_length}" rpy="0 0 0"/>
		<axis xyz="1 0 0"/>
	</xacro:ur_joint>

	<xacro:ur_joint name="wrist_2" parent="wrist_1_link" child="wrist_2_link">
		<origin xyz="0 0 ${elbow_offset}" rpy="0 0 0"/>
		<axis xyz="0 0 1"/>
	</xacro:ur_joint>
	
	<xacro:ur_joint name="wrist_3" parent="wrist_2_link" child="wrist_3_link">
		<origin xyz="0 ${-elbow_offset} 0" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
	</xacro:ur_joint>
	
</robot>
