hardware_interface:
  joints:
     - robotiq_85_left_knuckle_joint 

gripper:
  type: "position_controllers/GripperActionController"
  joint: robotiq_85_left_knuckle_joint
  stalled_velocity_threshold: 0.01
  stall_timeout: 0.1
  max_effort: 30
  gains:
    robotiq_85_left_knuckle_joint: {p: 1, i: 0, d: 0.1}
  

